/****************************************************************************************
Name            : ConstraintModel
Revision Log    : 8/12/2020 Bryan
                :
                :
Use             : Used with the CPQ API, DO NOT UPDATE VARIABLES UNLESS API CHANGES
*****************************************************************************************/
public with sharing class ConstraintModel {
    public SBQQ__OptionConstraint__c record;
    public Boolean priorOptionExists;
}